{% set name = "policy_sentry" %}
{% set version = "0.11.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/policy_sentry-{{ version }}.tar.gz
  sha256: ec4d6df39fb194ca551e6c4340be6ae04e6b9f76c956648e7371a571be881285

build:
  number: 0
  noarch: python
  entry_points:
    - policy_sentry=policy_sentry.bin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

test:
  imports:
    - policy_sentry
    - policy_sentry.analysis
  commands:
    - pip check
    - policy_sentry --help
  requires:
    - pip

about:
  home: https://github.com/salesforce/policy_sentry
  summary: Generate locked-down AWS IAM Policies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ForgottenProgramme
